### ISSUE TITLE
Assetmanager

### ISSUE THREAD

**Issue by Blueforcer** [awtrix/awtrix-hd#4]
When developing apps, it will be important to be able to include assets such as images or audio with the app.
If I remember correctly, at least the internal asset linking already works. But not from the own app folder.
When compiling or uploading the asstes would of course also be packed, and when downloading from the store also be unpacked again.

**Comment by padarom** [comment]
In order to fully support this we'll need `@awtrix/dev` to also watch the asset directory and copy assets on change to the temporary working directory.

Like you said, the frontend and backend already support app-specific assets.
